name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: leanprover/lean-action@v1.5.0
        with:
          use-github-cache: false
          build: false
      - run: lake build
